# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end


  config.vm.define "gatekeeper001" do |gatekeeper|
    gatekeeper.vm.box = ".box/virtualbox/gatekeeper-0.1.0.box"
  end
end
